class DataValidationException(Exception):
    def __init__(self, message):
        pass